name: clang-format-lint

on:
  push:
    paths:
      - "app/boards/**/*.c"
      - "app/include/**/*.h"
      - "app/src/**"
      - "app/drivers/**/*.c"
      - "app/drivers/**/*.h"
  pull_request:
    paths:
      - "app/boards/**/*.c"
      - "app/include/**/*.h"
      - "app/src/**"
      - "app/drivers/**/*.c"
      - "app/drivers/**/*.h"

jobs:
  build:
    runs-on: ubuntu-latest
    name: clang-format lint

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.9
        with:
          source: "./app"
          extensions: "h,c"
